# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "build"
  - "hawkscan"

steps:
  clone:
    when:
      branch:
        only:
          - master
          - /^codefresh.*/i
          - /^feature/codefresh.*/i
    title: "Cloning repository"
    type: "git-clone"
    repo: "kaakaww/hawkscan-cicd-integrations"
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  hawkscan-remote:
    title: "HawkScan Remote Test"
    type: "freestyle"
    image: "stackhawk/hawkscan"
    environment:
      - APP_ID=38144eb8-5e64-482d-b2c4-786c501710ba
      - HOST=http://example.com
      - REPO_DIR=${{CF_VOLUME_PATH}}/${{CF_REPO_NAME}}
      - ENV=Codefresh
    stage: "hawkscan"
    working_directory: IMAGE_WORK_DIR
    entrypoint: /bin/bash
    commands:
      - su --login --preserve-environment --command "PATH=$PATH:/zap shawk" zap
